name: tiny_charts
description: Render sparkline charts for fast data visualization on Flutter apps.
version: 0.1.0
repository: https://github.com/rows/tiny_charts
issue_tracker: https://github.com/rows/tiny_charts/issues
homepage: https://github.com/rows/tiny_charts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  vector_math: ^2.1.1
  meta: ^1.7.0
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.1
  flutter_test:
    sdk: flutter

flutter:
