name: pull-request

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  # BEGIN LINTING STAGE
  dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - uses: flame-engine/flame-dartdoc-action@v2

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - uses: flame-engine/flame-format-action@v1

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - uses: flame-engine/flame-analyze-action@v2
  # END LINTING STAGE

  # BEGIN TESTING STAGE
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - uses: flame-engine/flame-test-action@v1
  # END TESTING STAGE